import {
  ActionIcon,
  Alert,
  Badge,
  Button,
  Drawer,
  Menu,
  Paper,
  PasswordInput,
  SegmentedControl,
  TextInput,
  Tooltip,
  createTheme,
  type CSSVariablesResolver,
} from "@mantine/core"

import classes from "./theme.module.css"

const sans = '"Inter Variable", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif'
const mono = '"SFMono-Regular", Consolas, "Liberation Mono", ui-monospace, monospace'

export const designTokens = {
  color: {
    light: {
      canvas: "#e9ddcb",
      paper: "#fff9ee",
      paperMuted: "#f4eadb",
      paperStrong: "#e2d1bd",
      ink: "#2d1f19",
      muted: "#68594f",
      subtle: "#786a60",
      line: "#d0bda8",
      lineStrong: "#91786a",
      honey: "#bd6b49",
      honeyBorder: "#75432f",
      sage: "#126d69",
      sageSurface: "#d9ece7",
      sky: "#416c7b",
      skySurface: "#dce9eb",
      rust: "#a94436",
      rustStrong: "#7f3229",
      rustSurface: "#f4d9cf",
      panel: "#33231d",
      panelText: "#f5e7d3",
      focus: "#126d69",
      shadow: "rgba(63, 40, 29, 0.18)",
    },
    dark: {
      canvas: "#13100f",
      paper: "#211a17",
      paperMuted: "#1b1614",
      paperStrong: "#33251f",
      ink: "#f4e4ce",
      muted: "#cdb9a5",
      subtle: "#ad9988",
      line: "#49392f",
      lineStrong: "#755c4d",
      honey: "#d98a62",
      honeyBorder: "#a95f3d",
      sage: "#69c1b5",
      sageSurface: "#1c3632",
      sky: "#8fb8c4",
      skySurface: "#1c3036",
      rust: "#f08770",
      rustStrong: "#ffac95",
      rustSurface: "#42251f",
      panel: "#0b0908",
      panelText: "#f4e4ce",
      focus: "#69c1b5",
      shadow: "rgba(0, 0, 0, 0.42)",
    },
  },
  spacing: { 1: "4px", 2: "8px", 3: "12px", 4: "18px", 5: "24px", 6: "34px", 7: "48px" },
  radius: { xs: "3px", sm: "6px", md: "10px", lg: "14px", xl: "18px" },
  motion: {
    fast: "120ms",
    standard: "180ms",
    slow: "240ms",
    easing: "cubic-bezier(0.2, 0, 0, 1)",
  },
  layout: {
    prose: "760px",
    content: "1000px",
    shell: "1460px",
    compact: "43.75em",
    navigation: "56.25em",
  },
  icon: { inline: "16px", control: "18px", standalone: "20px" },
} as const

export type SemanticColors = { [Key in keyof (typeof designTokens.color)["light"]]: string }

export function semanticVariables(colors: SemanticColors) {
  return {
    "--ds-canvas": colors.canvas,
    "--ds-paper": colors.paper,
    "--ds-paper-muted": colors.paperMuted,
    "--ds-paper-strong": colors.paperStrong,
    "--ds-ink": colors.ink,
    "--ds-muted": colors.muted,
    "--ds-subtle": colors.subtle,
    "--ds-line": colors.line,
    "--ds-line-strong": colors.lineStrong,
    "--ds-accent": colors.honey,
    "--ds-accent-border": colors.honeyBorder,
    "--ds-accent-surface": `color-mix(in srgb, ${colors.honey} 14%, ${colors.paper})`,
    "--ds-primary": colors.sage,
    "--ds-primary-border": colors.sage,
    "--ds-safe": colors.sage,
    "--ds-safe-surface": colors.sageSurface,
    "--ds-info": colors.sky,
    "--ds-info-surface": colors.skySurface,
    "--ds-orange": colors.honey,
    "--ds-teal": colors.sage,
    "--ds-zinc-blue": colors.sky,
    "--ds-walnut": colors.panel,
    "--ds-beige": colors.canvas,
    "--ds-honey": colors.honey,
    "--ds-honey-border": colors.honeyBorder,
    "--ds-sage": colors.sage,
    "--ds-sage-surface": colors.sageSurface,
    "--ds-sky": colors.sky,
    "--ds-sky-surface": colors.skySurface,
    "--ds-rust": colors.rust,
    "--ds-rust-strong": colors.rustStrong,
    "--ds-rust-surface": colors.rustSurface,
    "--ds-panel": colors.panel,
    "--ds-panel-text": colors.panelText,
    "--ds-focus": colors.focus,
    "--ds-shadow-color": colors.shadow,
    "--mantine-color-dimmed": colors.muted,
    "--ds-glass": `color-mix(in srgb, ${colors.paper} 44%, transparent)`,
    "--ds-glass-strong": `color-mix(in srgb, ${colors.paper} 64%, transparent)`,
    "--ds-glass-overlay": `color-mix(in srgb, ${colors.paper} 86%, transparent)`,
    "--ds-glass-line": `color-mix(in srgb, ${colors.lineStrong} 44%, transparent)`,
    "--ds-glass-highlight": `color-mix(in srgb, ${colors.paper} 88%, transparent)`,
    "--ds-glass-refraction": `color-mix(in srgb, ${colors.sky} 16%, transparent)`,
  }
}

export const cssVariablesResolver: CSSVariablesResolver = () => ({
  variables: {
    "--ds-font-sans": sans,
    "--ds-font-mono": mono,
    "--ds-space-1": designTokens.spacing[1],
    "--ds-space-2": designTokens.spacing[2],
    "--ds-space-3": designTokens.spacing[3],
    "--ds-space-4": designTokens.spacing[4],
    "--ds-space-5": designTokens.spacing[5],
    "--ds-space-6": designTokens.spacing[6],
    "--ds-space-7": designTokens.spacing[7],
    "--ds-radius-xs": designTokens.radius.xs,
    "--ds-radius-sm": designTokens.radius.sm,
    "--ds-radius-md": designTokens.radius.md,
    "--ds-radius-lg": designTokens.radius.lg,
    "--ds-radius-xl": designTokens.radius.xl,
    "--ds-motion-fast": designTokens.motion.fast,
    "--ds-motion-standard": designTokens.motion.standard,
    "--ds-motion-slow": designTokens.motion.slow,
    "--ds-motion-easing": designTokens.motion.easing,
    "--ds-prose-width": designTokens.layout.prose,
    "--ds-content-width": designTokens.layout.content,
    "--ds-shell-width": designTokens.layout.shell,
    "--ds-icon-inline": designTokens.icon.inline,
    "--ds-icon-control": designTokens.icon.control,
    "--ds-icon-standalone": designTokens.icon.standalone,
    "--ds-on-accent": "#21140f",
    "--ds-on-honey": "#21140f",
    "--ds-pixel-unit": "4px",
    "--ds-glass-blur": "26px",
    "--ds-glass-saturate": "1.28",
    "--ds-glass-brightness": "1.04",
    "--ds-glass-contrast": "1.02",
    "--ds-glass-sheen": "linear-gradient(135deg, color-mix(in srgb, var(--ds-glass-highlight) 44%, transparent), transparent 38%, color-mix(in srgb, var(--ds-glass-refraction) 40%, transparent) 68%, transparent)",
    "--ds-shadow-xs": "2px 2px 0 var(--ds-shadow-color)",
    "--ds-shadow-sm": "0 8px 18px -14px color-mix(in srgb, var(--ds-ink) 42%, transparent)",
    "--ds-shadow-md": "0 18px 40px -28px color-mix(in srgb, var(--ds-ink) 46%, transparent)",
    "--ds-shadow-lg": "0 24px 58px -30px color-mix(in srgb, var(--ds-ink) 52%, transparent)",
    "--ds-shadow-xl": "0 30px 72px -34px color-mix(in srgb, var(--ds-ink) 58%, transparent)",
    "--ds-shadow-float": "0 24px 64px -28px color-mix(in srgb, var(--ds-ink) 52%, transparent), 0 8px 22px -16px color-mix(in srgb, var(--ds-sky) 40%, transparent), inset 0 1px 0 var(--ds-glass-highlight), inset 0 -1px 0 var(--ds-glass-refraction)",
  },
  light: semanticVariables(designTokens.color.light),
  dark: semanticVariables(designTokens.color.dark),
})

const inputClassNames = {
  label: classes.inputLabel,
  description: classes.inputDescription,
  input: classes.input,
  error: classes.inputError,
}

export const theme = createTheme({
  primaryColor: "sage",
  primaryShade: 7,
  autoContrast: true,
  luminanceThreshold: 0.45,
  black: designTokens.color.light.ink,
  white: designTokens.color.light.paper,
  colors: {
    honey: ["#fbf1ec", "#f5dfd5", "#ebc3b1", "#dfa288", "#d08362", "#bd6b49", "#a7593b", "#8d4c35", "#75432f", "#5f3729"],
    sage: ["#ecf8f5", "#d9ece7", "#b5ddd5", "#87c8bd", "#58aea4", "#319188", "#187b75", "#126d69", "#105754", "#0e4543"],
    sky: ["#f0f7f8", "#dce9eb", "#bfd8de", "#99c0ca", "#73a7b4", "#588d9c", "#416c7b", "#345866", "#2b4853", "#243a43"],
    rust: ["#fff3ed", "#fbe2d6", "#f3c1aa", "#e99b79", "#de7952", "#c85f3d", "#a94b31", "#873d2b", "#6d3327", "#572b23"],
  },
  fontFamily: sans,
  fontFamilyMonospace: mono,
  headings: { fontFamily: sans, fontWeight: "600", textWrap: "balance" },
  defaultRadius: "md",
  radius: designTokens.radius,
  spacing: {
    xs: designTokens.spacing[2],
    sm: designTokens.spacing[3],
    md: designTokens.spacing[4],
    lg: designTokens.spacing[5],
    xl: designTokens.spacing[6],
  },
  breakpoints: {
    xs: "30em",
    sm: designTokens.layout.compact,
    md: designTokens.layout.navigation,
    lg: "75em",
    xl: "90em",
  },
  shadows: {
    xs: "var(--ds-shadow-xs)",
    sm: "var(--ds-shadow-sm)",
    md: "var(--ds-shadow-md)",
    lg: "var(--ds-shadow-lg)",
    xl: "var(--ds-shadow-xl)",
  },
  other: {
    motion: designTokens.motion,
    layout: designTokens.layout,
    icon: designTokens.icon,
  },
  respectReducedMotion: true,
  cursorType: "pointer",
  components: {
    Button: Button.extend({
      defaultProps: { variant: "default", radius: "md" },
      classNames: { root: classes.buttonRoot, label: classes.buttonLabel, section: classes.buttonSection },
    }),
    ActionIcon: ActionIcon.extend({
      defaultProps: { variant: "default", radius: "md" },
      classNames: { root: classes.actionIconRoot },
    }),
    SegmentedControl: SegmentedControl.extend({
      defaultProps: { radius: "md", withItemsBorders: false },
      classNames: {
        root: classes.segmentedRoot,
        label: classes.segmentedLabel,
        indicator: classes.segmentedIndicator,
      },
    }),
    Paper: Paper.extend({ defaultProps: { radius: "md" }, classNames: { root: classes.paperRoot } }),
    Alert: Alert.extend({
      defaultProps: { radius: "md", variant: "light" },
      classNames: { root: classes.alertRoot, title: classes.alertTitle, message: classes.alertMessage },
    }),
    Badge: Badge.extend({
      defaultProps: { radius: "sm", variant: "light", color: "sage" },
      classNames: { root: classes.badgeRoot, label: classes.badgeLabel },
    }),
    TextInput: TextInput.extend({ classNames: inputClassNames }),
    PasswordInput: PasswordInput.extend({ classNames: inputClassNames }),
    Menu: Menu.extend({ classNames: { dropdown: classes.dropdown, item: classes.menuItem, divider: classes.divider } }),
    Tooltip: Tooltip.extend({ classNames: { tooltip: classes.tooltip } }),
    Drawer: Drawer.extend({
      defaultProps: { radius: "lg" },
      classNames: {
        content: classes.drawerContent,
        header: classes.drawerHeader,
        body: classes.drawerBody,
        title: classes.drawerTitle,
      },
    }),
  },
})
